### ISSUE TITLE
Click-Off before selecting another feature

### ISSUE THREAD

**Issue by erochest** [scholarslab/NeatlineFeatures#12]
When editing features, sometimes you have to click off of the currently selected feature before you can select another one. This is unintuitive and needs to be fixed.

**Comment by davidmcclure** [comment]
Yes, I am constantly annoyed by this in NL as well. The problem is somewhere in my select/edit/deselect code in the neatlinemap widget. I've made a couple of half-hearted sallies at trying to fix this, but couldn't ever reliably reproduce the issue (sometimes, it works just fine). From a _feel_ standpoint, though, this is a major sticky point.

**Comment by erochest** [comment]
I've been testing this off and on, and it seems to have shaken loose. I'll re-open if I notice it again.
